### ISSUE TITLE
Webhook issue

### ISSUE THREAD

**Issue by Webdeb08** [itskekoff/discord-server-copy#12]
After some message sended by webhooks there is an error appearing, fix it pls

**Comment by itskekoff** [comment]
send me error that you getting

**Comment by Webdeb08** [comment]
![Screenshot_2023-04-05-16-36-57-335_com android chrome](https://user-images.githubusercontent.com/129002662/230063232-7923fc2c-6570-41b3-91cf-b52683f14832.png)
![Screenshot_2023-04-05-16-36-36-355_com android chrome](https://user-images.githubusercontent.com/129002662/230063239-3ecfc86a-5afa-47d1-b56b-9c5389a3649c.png)
This is generally coming again and again idk why
