### ISSUE TITLE
Can I join the project? I can improve it 

### ISSUE THREAD

**Issue by Jeremyop** [itskekoff/discord-server-copy#13]
Can I join the project? I can improve it

**Comment by Webdeb08** [comment]
Do you have any solution of  error, formdata has no len ()/ nonetype has no len () , after some msgs sent by Webhook this error appears

**Comment by Jeremyop** [comment]
What is your discord?let me add you

**Comment by itskekoff** [comment]
> Can I join the project? I can improve it

send some pull requests thats improves my code
