### ISSUE TITLE
lmao sorry 

### ISSUE THREAD

**Issue by Fluff4life** [itskekoff/discord-server-copy#21]
It doesn't clone all the channels, but it doesn't tell me there is an error

**Comment by itskekoff** [comment]
> It doesn't clone all the channels, but it doesn't tell me there is an error

but it clones text & voice channels?

**Comment by itskekoff** [comment]
ok it can't clone stage channels, temporary removed in it 1.3.1 version.

**Comment by Fluff4life** [comment]
> > It doesn't clone all the channels, but it doesn't tell me there is an error
> 
> but it clones text & voice channels?

I meant it doesn't clone all of the text and voice channels. It clones most of them, but other ones don't get created.
