### ISSUE TITLE
message forwarding not resuming after crash

### ISSUE THREAD

**Issue by eduDev81** [itskekoff/discord-server-copy#31]
Sorry if this is not a bug, maybe just a question.

When I ran main.py all worked fine and messages were getting forwarded from one server to another as they arrive.

However my terminal crashed (im in macbook), so I re-started terminal, re-ran main.py, it tells logged as xxxxx successfully, but messages are no longer forwarded from one server to another as they arrive.

Am I doing something wrong here?.

**Comment by itskekoff** [comment]
You can't do anything with that. this is not a bug. message forwarding doesn't supports auto resuming on application restart
