### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access 

### ISSUE THREAD

**Issue by hoangbits** [itskekoff/discord-server-copy#37]
I got this error while trying to copy messages
![image](https://github.com/itskekoff/discord-server-copy/assets/7990827/0152e41f-0902-4549-afa2-4a771c2e3d71)
![image](https://github.com/itskekoff/discord-server-copy/assets/7990827/94881a0e-0b75-47a0-933f-3c06f893f7fc)

**Comment by itskekoff** [comment]
u don't have access to view channel messages, just wait till bot caches all messages  that it can and starts cloning (or u can just disable clone_queue in config to avoid this)
