### ISSUE TITLE
How to change UTC 24h to CST America/Chicago 12h?

### ISSUE THREAD

**Issue by pnydiffuser** [itskekoff/discord-server-copy#40]
the processed messages give a time format different from where i live, unable to tell when they were really sent.

![Screenshot_2024-02-04_09-54-29](https://github.com/itskekoff/discord-server-copy/assets/131926673/7bd79bb2-5739-444f-ac0e-9f6dca369167)

**Comment by itskekoff** [comment]
u can't change this
