### ISSUE TITLE
Help me how to make him start copying messages

### ISSUE THREAD

**Issue by Germanso88** [itskekoff/discord-server-copy#42]
I have all the channels copied and the message is not just stuck on [GTA 5 RP | EMS/INFO] | Processing server messages... Help me figure it out

**Comment by jacobjonz** [comment]
I am having the same issue.

On a quick debug, I have found two things. Not sure if it is fully correct.

1. if the queue is enabled, it does not seem to be going for the history.
    `tasks.append(self.clone_channel_messages(channel, limit, clear))`
    is not called in         
    `if self.clone_parallel and self.clone_queue:`

2. It actually reads the message and reaches the semaphore_task and is awaiting
    `func(*args, **kwargs)`

**Comment by Germanso88** [comment]
And how to fix it ?

**Comment by jacobjonz** [comment]
I don't know either. I was hoping someone would help. Just added my findings. That's all.

**Comment by itskekoff** [comment]
Your messages are adding to queue, u can disable queue and messages will copy immediately

**Comment by jacobjonz** [comment]
I did try with queue disabled, but without avail.
