### ISSUE TITLE
How to clone message history

### ISSUE THREAD

**Issue by Keidi-Teixeira** [itskekoff/discord-server-copy#43]
i have my config.json set like this and i am using this command to close the server : cp!clone but it won't clone the message history. i saw something about the queue so i thought that disabling it would solve but it didn't.
{
  "token": "",
  "prefix": "cp!",
  "debug": true,
  "clone_settings": {
    "name_syntax": "%original%-copy",
    "clone_delay": 1.337,
    "clear_guild": true,
    "icon": true,
    "banner": true,
    "roles": true,
    "channels": true,
    "overwrites": true,
    "emoji": false,
    "stickers": false
  },
  "clone_messages": {
    "comment": "Clone messages in all channels (last messages). Long limit - long time need to copy",
    "enabled": true,
    "comment_use_queue": "Clone messages using queue for each channels and caches all messages before sending",
    "use_queue": false,
    "oldest_first": true,
    "comment_parallel": "Clone messages for all channels (can be used with queue)",
    "parallel": true,
    "webhooks_clear": true,
    "limit": 8196,
    "delay": 0.65
  },
  "live_update": {
    "comment": "Automatically detect new messages and send it via webhook",
    "comment_2": "Also works with clone_messages (starts sending when channel is fully processed)",
    "enabled": false,
    "message_delay": 0.75
  }
}

**Comment by itskekoff** [comment]
maybe u don't have access to view channel history? idk but it works for me 100000%, i tested.

**Comment by Keidi-Teixeira** [comment]
i have adm

**Comment by itskekoff** [comment]
will be fixed in next update, btw can u send link to the server where u can't copy?

**Comment by Keidi-Teixeira** [comment]
i am not in that server anymore, i left, but i also tried with other ones that i have adm with and without onboarding enabled (in case it could be it) and it did copied everything but the message history, emojis, stickers and messages.

**Comment by MrFiNka** [comment]
> будет исправлено в следующем обновлении, кстати, вы можете отправить ссылку на сервер, на который вы не можете скопировать?

How soon will the update be rolled?

**Comment by mike777z** [comment]
+1

**Comment by itskekoff** [comment]
> How soon will the update be rolled?

братик, я хз, у меня пока нету желания над этим работать, но ты можешь попробовать исправить сам, если сможешь - открывай pull request

> i am not in that server anymore, i left, but i also tried with other ones that i have adm with and without onboarding enabled (in case it could be it) and it did copied everything but the message history

send me link to discord server where this "error" appears

**Comment by gitYannaws** [comment]
Server message history isn't working for me either but everything else looks good, do you want to be added to my server?

**Comment by itskekoff** [comment]
maybe fixed in new update, try to reset your config and read README.MD to figure out about update
