### ISSUE TITLE
Always stuck at same step and forum not copied

### ISSUE THREAD

**Issue by EmmanuelDevienne** [itskekoff/discord-server-copy#45]
The process is always stay at step 
`Processing community settings & additional channels...`

And the forum are not copied 
I see for exemple a forum in the log but is not copied 
`Got overwrites mapping for channel #program-follow-up`

**Comment by itskekoff** [comment]
send me link to discord server where u can't copy

**Comment by pnydiffuser** [comment]
I have removed lines 264-267 in main.py to get around this a month ago.
It's likely not a default config variable, as the lines above it reference "role" "icon" "emojis" etc.
Untested, but manually enabling community might also work during setup.
