### ISSUE TITLE
friend help me go on Discord I'll show you a demo 

### ISSUE THREAD

**Issue by kniknivadim** [itskekoff/discord-server-copy#46]
It starts for me and says: 
![Discord_Server_Copier_20 03 2024_15_30_47](https://github.com/itskekoff/discord-server-copy/assets/137409582/4fdda2d3-2981-4c88-b8ea-16c01ad931d3)

**Comment by itskekoff** [comment]
используй discord.py-self, а не discord.py.

pip uninstall discord.py
pip install discord.py-self
