### ISSUE TITLE
Stuck after Logged as ...

### ISSUE THREAD

**Issue by micahz13** [itskekoff/discord-server-copy#47]
v10:44:19 | [MAIN/SUCCESS] | Logged on as ******

![image](https://github.com/itskekoff/discord-server-copy/assets/74470233/9168825c-ea20-447c-a810-5ecea4d5839f)

**Comment by itskekoff** [comment]
bot is awaiting for commands. If u sure that u sent command - check logs and send it to me (if any errors)
