### ISSUE TITLE
Copying Messages doesn't fully work

### ISSUE THREAD

**Issue by Mehmorel** [itskekoff/discord-server-copy#50]
Copying Messages is working since last update(s), but it doesn't copy ALL the messages for me.
my settings:
{
  "prefix": "cp!",
  "debug": true,
  "clone_settings": {
    "name_syntax": "x",
    "clone_delay": 1.337,
    "clear_guild": true,
    "icon": true,
    "banner": true,
    "roles": true,
    "channels": true,
    "overwrites": true,
    "emoji": true,
    "stickers": false
  },
  "clone_messages": {
    "__comment__": "Clone messages in all channels (last messages). Long limit - long time need to copy",
    "enabled": true,
    "oldest_first": true,
    "webhooks_clear": true,
    "limit": 8196,
    "delay": 0.65
  },
  "live_update": {
    "__comment__": "Automatically detect new messages and send it via webhook",
    "__comment2__": "Also works with clone_messages (starts sending when channel is fully processed)",
    "enabled": true,
    "message_delay": 0.75
  }
}

**Comment by itskekoff** [comment]
do you have discord error logs? check file that ends with 2024-discord.log

**Comment by itskekoff** [comment]
possibly fixed in new updates. update and use cp!help to get info about commands.
