### ISSUE TITLE
WARNING We are being rate limited

### ISSUE THREAD

**Issue by MrFiNka** [itskekoff/discord-server-copy#51]
[28-04-2024-discord.log](https://github.com/itskekoff/discord-server-copy/files/15142508/28-04-2024-discord.log)

**Comment by MrFiNka** [comment]
Please make at least some decision

**Comment by Mehmorel** [comment]
i have the same thing

**Comment by itskekoff** [comment]
increase webhook_delay in config.json. Recommended value: 1.95
