### ISSUE TITLE
Can't copy all channels

### ISSUE THREAD

**Issue by Fluff4life** [itskekoff/discord-server-copy#52]
It can't copy all channels
19:08:32 | [Main/DEBUG] | Can't fetch channel Staff 「📣」 | 1122650917032972438
19:08:32 | [Main/DEBUG] | Can't fetch channel 「🫧」staff-chat | 1122650917276233728
19:08:32 | [Main/DEBUG] | Can't fetch channel [🔊]  Staff VC | 1122650917276233729
19:08:33 | [Main/DEBUG] | Can't fetch channel 「🗒」logs | 1122650917276233731
It say's cant fetch instead saying "got overwrite mapping for "#example"  and "created #example)

**Comment by Mehmorel** [comment]
you dont have permissions to this channels

**Comment by Fluff4life** [comment]
> you dont have permissions to this channels

The version before the new version, it was able to copy all channels. Even private ones

**Comment by itskekoff** [comment]
Now you can disable channel fetching using argument (disable_fetch_channels=True). Reason of this error: you don't have access to view channel.

**Comment by Fluff4life** [comment]
> Now you can disable channel fetching using argument (disable_fetch_channels=True). Reason of this error: you don't have access to view channel.

If you do this, you can copy servers again?
