### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by MrFiNka** [itskekoff/discord-server-copy#53]
![Screenshot_2024-04-30-16-13-31-87_84d3000e3f4017145260f7618db1d683](https://github.com/itskekoff/discord-server-copy/assets/48646488/1e0007db-4c41-4572-93fe-f0edf6edf905)

**Comment by MrFiNka** [comment]
For some reason, I don't have a log file, so can I send it to you?

**Comment by MrFiNka** [comment]
Please add a counter of sent messages, like in my screenshot

**Comment by MrFiNka** [comment]
> ![Screenshot_2024-04-30-16-13-31-87_84d3000e3f4017145260f7618db1d683](https://private-user-images.githubusercontent.com/48646488/326820179-1e0007db-4c41-4572-93fe-f0edf6edf905.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODYwNDYsIm5iZiI6MTcxNDQ4NTc0NiwicGF0aCI6Ii80ODY0NjQ4OC8zMjY4MjAxNzktMWUwMDA3ZGItNGM0MS00NTcyLTkzZmUtZjBlZGY2ZWRmOTA1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE0MDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzOGM1NmNjMmI5OWVhMmJkOWEyNTAwYmIwYmFmNTdiMTYxMGIxMWMxOTczMjEyMjJlY2Q2MDU3NWNhMDIwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.biypGTTgOKWFWApKUNSpxyZr0SmVSv0maTCb-WR-6bQ)
[30-04-2024-discord.log](https://github.com/itskekoff/discord-server-copy/files/15165488/30-04-2024-discord.log)

**Comment by itskekoff** [comment]
это у тебя проблемы с соединением к вебсокету, лучшее решение это либо не выключать телефон не давать ему гаснуть (тем самым подключение не сбросится если интернет отключается при выключении экрана), либо как я сделал - купить VPS/VDS, главное чтобы оперативки было минимум 2 гига, желательно 4 чтобы точно копировало сообщения нормально (т.е потребление оперативы напрямую зависит от количества сообщений и того, что в сообщении), т.к оно их кэширует и оно находится в памяти. Про подсчет сообщений я уже думал, попробую реализовать.
