### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by swat-jpg** [itskekoff/discord-server-copy#55]
![image](https://github.com/itskekoff/discord-server-copy/assets/79261470/7c5d8ce0-d858-4921-926f-d04002f05cc3)
help

**Comment by Fluff4life** [comment]
It creates a file in your folder "Re-created it", you have to find the config.json file and configure it. (I feel like you are on the younger side tbh, sorry for going out of pocket)

**Comment by itskekoff** [comment]
bro wtf, you put IN WINDOWS/SYSTEM32?? create folder on your desktop/documents, put all from repository and do it again. configuration will be created.
