### ISSUE TITLE
why

### ISSUE THREAD

**Issue by luckindtune** [itskekoff/discord-server-copy#60]
C:\Windows\system32>python main.py
Traceback (most recent call last):
  File "C:\Windows\system32\main.py", line 15, in <module>
    from modules.updater import Updater
  File "C:\Windows\system32\modules\updater.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by ammystic** [comment]
this is your fault btw.
open a cmd window in the main folder and run "pip install -r requirements.txt"

**Comment by itskekoff** [comment]
pip install -r requirements.txt

**Comment by swat-jpg** [comment]
i get the same issue as u even after installing the requirements 
![image](https://github.com/itskekoff/discord-server-copy/assets/79261470/8874acf2-0c59-41df-8afe-bce05619ccce)

**Comment by itskekoff** [comment]
pip install requests

**Comment by swat-jpg** [comment]
look above i already ran the command
