### ISSUE TITLE
copying messages stopped midway

### ISSUE THREAD

**Issue by SeratulA** [itskekoff/discord-server-copy#61]
The program was running for a couple hours and it seems that maybe the limit was reached and it stopped. However, there is still a lot of messages needed to be copied. Do you know how I could tweak the code and just have it pull from one specific channel after a specific date into a channel that was already being populated by the program?

**Comment by itskekoff** [comment]
You can't do this. After restart, mappings for channels and webhooks will be cleared, so you can't restore copying. About "it stopped" - do you have discord logs?

**Comment by SeratulA** [comment]
Basically since the limit was set by default to about 8000 messages, it stopped going afterwards. However, I changed it, I also deleted the portion where it clears all the server names and channels and I edited the self.mappings["fetched_data"]["channels"] to only have the channel I needed. I tried it on a different server, and it seems to duplicate everything, but it doesnt delete anything which is fine cause I can delete the duplicated roles and everything myself. My new question is do you know where I can add a timestamp to it. I tried messing around the code so the server doesn't look for messages before a certain date, but I'm still having bugs with it. Any tips?

**Comment by SeratulA** [comment]
The reason I'm asking this is cause I'm trying to copy a sever in which my irl friends have had since 2020. The owner is no longer communicating with us so I'm trying to make a new server and keep all the memories in one place.
