### ISSUE TITLE
Cloning select channels in a server to avoid message download overload

### ISSUE THREAD

**Issue by diliprk** [itskekoff/discord-server-copy#68]
Hi, I tried cloning all the channels from this `https://discord.com/channels/1031673556586741830` goes by the name of `PepeThugLife's Casino`  (Join his discord from this link - https://linktr.ee/pepethuglife ) . It has ~ 50+ channels with lots of message history, so when I ran the command 
`cp!clone live_update=true clone_message=true real_time_messages=true process_new_messages=true` in the `general-chat` of the channel , the `discord-server-copy` started recreating a complete cloned copy of the source server. Though it created the names, roles, icons of the channels the past message history did not appear, probably because of too many messages to download. Recent messages that were posted after the server channel has been cloned also appeared, but not all the past historical messages.
<img width="1434" alt="failed_chat_hist_download" src="https://github.com/itskekoff/discord-server-copy/assets/20330371/196f5217-31e0-4b0d-981d-b50306701140">

My question, how do I restrict the `discord-server-copy` to only download the past message history for select channels?
Can't see something like this in the `config.json` options?

**Comment by itskekoff** [comment]
you mean copying specified channels? if yes, i can add this.

**Comment by diliprk** [comment]
Yes I mean specific channels, so that the API rate limit is not hit, also if there is a way to initiate the cloning process without typing any commands in the discord channels of other people, please let us know. As I got banned from one channel

**Comment by pnydiffuser** [comment]
Try using the clone command in a new server, it works without having to use within the source server.

**Comment by diliprk** [comment]
Hi @itskekoff , were you able to make any changes to the repo, to exclude certain channels from the cloning process?

**Comment by itskekoff** [comment]
maybe.
