### ISSUE TITLE
Cloned messages dont show as a reply if they are a reply to a previous message

### ISSUE THREAD

**Issue by sarthakmehra27** [itskekoff/discord-server-copy#73]
Firstly, great work on the bot @itskekoff ! i want to ask a few queries:

If there is a message which is a reply to an existing message, the bot will not consider the reply while cloning the message. Check in the example image:
Original Message
![image](https://github.com/user-attachments/assets/c2b49127-1a57-455d-b6f9-046006cc57b0)
Cloned Message: 
![image](https://github.com/user-attachments/assets/f0df60c0-55df-4940-854d-ebfe6148b454)
As seen, which cloning the message, it is not sent as a reply to another message which mainly breaks the flow of the conversation.

2. After the initial clone of the structure of a discord server, how do i just start cloning the live messages? i coudn't figure that out. 

3. How can i start cloning messages from different servers into their clone servers simultaneously? say i have the clone of 10 servers and i want to clone live messages from all 10 into their clone servers simultaneously. Can i do that?

4. Can the bot be setup to keep doing its job in the background? Right now i open cmd, run the bot and it keeps working till cmd is open.

Im mainly from Java background so if some of my questions are obvious for a python dev, please guide me there :)

thanks!

**Comment by sarthakmehra27** [comment]
Hi @itskekoff. Can you reply please? Thanks.

**Comment by itskekoff** [comment]
1. webhook's can't reply.
2. before clone enable live_update or smth similar in config or command
3. yes u can
4. currently no, and it is not useful
