### ISSUE TITLE
Threads & Forum channels

### ISSUE THREAD

**Issue by Mehmorel** [itskekoff/discord-server-copy#74]
when or rather whether it will be possible to copy forum channels and threads?

**Comment by itskekoff** [comment]
please send me discord invite where cloning is not works so i can test bot.

**Comment by anonymo006** [comment]
When I successfully cloned a server, including live messages, and it worked fine, I was annoyed that the script stopped accidentally. Restarting the bot would begin the process from the beginning, clearing guild, cloning channels, roles, and messages. Is it possible to resume the bot from where it left off?
