### ISSUE TITLE
Resume Cloning Process on Bot Restart

### ISSUE THREAD

**Issue by anonymo006** [itskekoff/discord-server-copy#76]
When I successfully cloned a server, including live messages, and it worked fine, I was annoyed that the script stopped accidentally. Restarting the bot would begin the process from the beginning, clearing guild, cloning channels, roles, and messages. Is it possible to resume the bot from where it left off?

**Comment by itskekoff** [comment]
no.

**Comment by anonymo006** [comment]
When the script is cloning channels and guilds, we can save the channel IDs. If the script stops, we can enable live message cloning and disable the previous message cloning and clearing features. This way, live messages can be sent to the saved channel IDs. When we run the script again, it should check for the saved channel or guild IDs and use them to send live messages to the designated channels.
