### ISSUE TITLE
stuck after login 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [itskekoff/discord-server-copy#78]
[Main/SUCCESS] | Logged on as **********************
[Main/INFO] | Loaded 1 extensions, with total of 2 command

it stuck after login and i cant enter any command

**Comment by anonymo006** [comment]
bro after login go back to your discord account and create a fake server and that server type cp!help
you will see a list of command to use .this script work through discord not in terminal

**Comment by BLACKGAMER1221** [comment]
oh ok thank you
