### ISSUE TITLE
Error when running python3 main.py

### ISSUE THREAD

**Issue by Fluff4life** [itskekoff/discord-server-copy#8]
Traceback (most recent call last):
  File "/home/runner/discord-server-copy-1/main.py", line 332, in <module>
    bot = commands.Bot(command_prefix=prefix, case_insensitive=True,
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by itskekoff** [comment]
make sure that you use discord.py-self instead of discord.py
