### ISSUE TITLE
Live messages if i am offline

### ISSUE THREAD

**Issue by thefoufoufou** [itskekoff/discord-server-copy#80]
Hello,

I wanted to know if messages sent live are only retrieved if my account is online when they are sent, or if they are retrieved even if I'm offline?

If they aren't retrieved because I'm offline, will they be retrieved as soon as I log in? 

If they aren't retrieved, what can I do to get them?

Thank you

**Comment by itskekoff** [comment]
messages can be cloned while BOT is running

if bot is not running - no messages

if not retrieved (also if bot is running) - you can't get it again (only clone again)
