### ISSUE TITLE
threads channel not cloning 

### ISSUE THREAD

**Issue by anonymo006** [itskekoff/discord-server-copy#81]
The threads and forun channels not cloning .

**Comment by itskekoff** [comment]
error log?

**Comment by anonymo006** [comment]
no bro the message in the thread not cloning or sending  .

**Comment by itskekoff** [comment]
messages in thread not cloning?

**Comment by anonymo006** [comment]
yes .can u give your contact so i can share the discord link .

**Comment by itskekoff** [comment]
no, thread messages cannot be cloned.

**Comment by itskekoff** [comment]
currently impossible for me or idk how to do this

**Comment by anonymo006** [comment]
can u give or telegram id or something to contact u ?we can work together

**Comment by itskekoff** [comment]
t.me/vmprotectx64
