### ISSUE TITLE
improvement for cloning.

### ISSUE THREAD

**Issue by anonymo006** [itskekoff/discord-server-copy#82]
When the script is cloning channels and guilds, we can save the channel IDs. If the script stops, we can enable live message cloning and disable the previous message cloning and clearing features. This way, live messages can be sent to the saved channel IDs. When we run the script again, it should check for the saved channel or guild IDs and use them to send live messages to the designated channels.

**Comment by itskekoff** [comment]
ok, will be in future update

**Comment by anonymo006** [comment]
bro how i can contact you ?
